[package]
name = "ink-analyzer"
version = "0.3.0"
edition = "2021"
description = "A library for semantic analysis of ink! smart contract code."
license = "MIT OR Apache-2.0"
authors = ["David Semakula <hello@davidsemakula.com>"]

readme = "README.md"
repository = "https://github.com/ink-analyzer/ink-analyzer"
homepage = "https://github.com/ink-analyzer/ink-analyzer"
keywords = ["ink", "smart-contract", "polkadot", "substrate", "blockchain"]
categories = ["development-tools"]

[dependencies]
ink-analyzer-ir = { path = "../ir" }
