[package]
name = "test-utils"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
crossbeam-channel = "0.5.14"
lsp-server = "0.7.8"
lsp-types = { version = "0.97.0", features = ["proposed"] }
serde_json = "1.0.140"
url = "2.5.4"