name: CI

on: [ push, pull_request ]

env:
  RUSTFLAGS: "-D warnings"

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        run: rustup update
      - name: Run lints
        run: cargo clippy --verbose
      - name: Run build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
